### ISSUE TITLE
 why not subclassing your KVOMutableArray to NSMutableArray

### ISSUE THREAD

**Issue by ChenYilong** [haifengkao/KVOMutableArray#1]
why not subclassing your KVOMutableArray to NSMutableArray, KVOMutableArray can not support many method in NSMutableArray

**Comment by haifengkao** [comment]
KVC works only on getters and setters. If I subclass NSMutableArray, there won't be any getters and setters to be observed.

**Comment by ChenYilong** [comment]
how can i use many methods like enumerateObjectsUsingBlock ,arrayWithCapacity ?how can you enum your  KVOMutableArray.

**Comment by haifengkao** [comment]
you can use `for` loop

``` objc
 KVOMutableArray* array = [[KVOMutableArray alloc] init];
 [array addObject:@(42)];
 for (id object in array){
   NSLog(@"%@", object);
 }
```

If you need `enumerateObjectsUsingBlock` ,`arrayWithCapacity`, feel free to send a pull request.

**Comment by ChenYilong** [comment]
I have a question,If I  have a 

MutableArray like


	KVOMutableArray* array = [KVOMutableArray new];
	[array addObject:mutableArray1];
	[array addObject:mutableArray2];

I want to observe array,If mutableArray1 or mutableArray2 changed ,Is it necessary to make mutableArray1 and mutableArray2  as KVOMutableArray?

**Comment by haifengkao** [comment]
Yes. You can find an example in [HFTableCollectionBindingHelper](https://github.com/haifengkao/HFTableCollectionBindingHelper).

Search for the following function: 
`- (AMBlockToken*)observeNestedArray:(KVOMutableArray*)array secondaryTokens:(NSMutableArray*)secondaryTokens`

**Comment by haifengkao** [comment]
I figured out a way to subclass NSMutableArray. Now you can use it as a regular NSMutableArray.
