### ISSUE TITLE
Type arguments 

### ISSUE THREAD

**Issue by expkzb** [haifengkao/KVOMutableArray#3]
I can not declare a property like `@property (nonatomic, strong) KVOMutableArray<Person *> *datas;` although KVOMutableArray is a sub class of NSMutableArray. 
May be it's an Xcode bug. Any ideas?

**Comment by haifengkao** [comment]
http://www.miqu.me/blog/2015/06/09/adopting-objectivec-generics/
It seems that you need to add the generics to the KVOMutableArray declaration as well. 
I don't use generics myself.
If you do, please send me a pull request.
You just need 
1. replace `id` with `ObjectType` 
2. add the declaration `@interface KVOMutableArray<ObjectType> : NSMutableArray<NSFastEnumeration, NSMutableCopying, NSCoding, NSCopying>`
3. send a pull request :)
